[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc="0.8.23"
optimizer=true
optimizer_runs=200
viaIR=true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@uniswap-v3-core/contracts/=lib/uniswap-v3-core/contracts/',
  '@uniswap-v3-periphery/contracts/=lib/uniswap-v3-periphery/contracts/',
  '@abdk-libraries-solidity/=lib/abdk-libraries-solidity/',
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/forge-std/lib/ds-test/src/"
]