name: Next.js CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm i @rollup/rollup-linux-x64-gnu
      - run: npm test

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: registry.digitalocean.com/chain-owls/w3a-mvp-dapp-frontend-new:latest

      # - name: Publish Image to Container Registry
      #   uses: ripplr-io/docr-docker-publish@v1
      #   with:
      #     image_path: registry.digitalocean.com/chain-owls/w3a-mvp-dapp-frontend-new:latest
