name: Next.js CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '21.1.0'
      # - run: npm ci
      # - run: npm run build --if-present
      # # - run: npm i @rolgit sulup/rollup-linux-x64-gnu
      # # - run: npm test

      - uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - uses: 1password/load-secrets-action@v1
        env:
          DIGITALOCEAN_ACCESS_TOKEN: "op://GitHub/Digital Ocean token for GitHub/credential"

      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: $DIGITALOCEAN_ACCESS_TOKEN

      - name: Publish Image to Container Registry
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: chain-owls/w3a-mvp-dapp-frontend-new:latest
